2021-09-27T09:52:54.009Z ERROR webdriver: Request failed due to session is not created: No device matching the desired capabilities
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-27T09:52:54.013Z ERROR webdriver: session is not created: No device matching the desired capabilities
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-27T09:54:22.381Z ERROR webdriver: Request failed due to session is not created: No device matching the desired capabilities
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-27T09:54:22.382Z ERROR webdriver: session is not created: No device matching the desired capabilities
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/menu_screen_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/menu_screen_identify_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/speedbug_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/taxon_detail_screen_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/gallery_screen_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/about_page_should_render_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/menu_screen_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/menu_screen_identify_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/speedbug_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/taxon_detail_screen_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/gallery_screen_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/about_page_should_render_1920x1080_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
Generated base line image: /home/msharman/Projects/walta/visual-regression-testing/baseline-images/menu_screen_2560x1440_baseline.png. Manually verify image and remove the "_baseline" from the string to accept.
2021-09-28T04:41:09.774Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error while creating UiObject2 object
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-28T04:41:14.888Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error while creating UiObject2 object
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-28T04:41:20.185Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error while creating UiObject2 object
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-28T04:41:26.955Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error while creating UiObject2 object
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-28T04:41:33.265Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error while creating UiObject2 object
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-28T04:43:02.088Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error while creating UiObject2 object
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-28T04:43:08.989Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error while creating UiObject2 object
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-28T04:43:13.767Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error while creating UiObject2 object
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-28T04:43:18.523Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error while creating UiObject2 object
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-09-28T04:43:22.420Z ERROR webdriver: Request failed due to unknown error: An unknown server-side error occurred while processing the command. Original error: Error while creating UiObject2 object
    at getErrorFromResponseBody (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/utils.js:121:10)
    at Request._callback (/home/msharman/Projects/walta/node_modules/webdriverio/node_modules/webdriver/build/request.js:121:64)
    at Request.self.callback (/home/msharman/Projects/walta/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at Request.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at Request.EventEmitter.emit (domain.js:483:12)
    at IncomingMessage.<anonymous> (/home/msharman/Projects/walta/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
